# Generated by Django 4.1.5 on 2023-03-14 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uci', models.CharField(default='', max_length=255, verbose_name='uci')),
                ('san', models.CharField(default='', max_length=255, verbose_name='san')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fen', models.CharField(max_length=255, unique=True, verbose_name='fen')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.move')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='PositionInfo',
            fields=[
                ('fen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='training.position')),
                ('cp', models.IntegerField(verbose_name='cp')),
                ('mate', models.IntegerField(verbose_name='mate')),
                ('appearances', models.IntegerField(verbose_name='appearances')),
                ('white_win_percent', models.FloatField(verbose_name='white_win_percent')),
                ('black_win_percent', models.FloatField(verbose_name='black_win_percent')),
            ],
        ),
        migrations.CreateModel(
            name='PositionParsed',
            fields=[
                ('fen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='training.position')),
                ('pure_pos', models.CharField(default='', max_length=255, verbose_name='pure_pos')),
                ('white_to_move', models.BooleanField(default=True, verbose_name='white_to_move')),
                ('black_castle_qside', models.BooleanField(default=True, verbose_name='black_castle_qside')),
                ('black_castle_kside', models.BooleanField(default=True, verbose_name='black_castle_kside')),
                ('white_castle_qside', models.BooleanField(default=True, verbose_name='white_castle_qside')),
                ('white_castle_kside', models.BooleanField(default=True, verbose_name='white_castle_kside')),
                ('enpassant', models.CharField(max_length=7, verbose_name='enpassant')),
                ('0', models.IntegerField(verbose_name='no_capture_moves')),
                ('1', models.IntegerField(verbose_name='n_moves')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_runs', models.IntegerField(verbose_name='total_runs')),
                ('successful_runs', models.IntegerField(verbose_name='successful_runs')),
                ('total_branch_runs', models.IntegerField(verbose_name='total_branch_runs')),
                ('successful_branch_runs', models.IntegerField(verbose_name='successful_branch_runs')),
                ('training_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.training')),
            ],
        ),
        migrations.AddField(
            model_name='move',
            name='initial_fen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initial_fen', to='training.position'),
        ),
        migrations.AddField(
            model_name='move',
            name='new_fen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_fen', to='training.position'),
        ),
    ]
