# Generated by Django 4.1.5 on 2023-03-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positionparsed',
            name='0',
        ),
        migrations.RemoveField(
            model_name='positionparsed',
            name='1',
        ),
        migrations.AddField(
            model_name='positionparsed',
            name='n_moves',
            field=models.IntegerField(default='1', verbose_name='n_moves'),
        ),
        migrations.AddField(
            model_name='positionparsed',
            name='no_capture_moves',
            field=models.IntegerField(default='0', verbose_name='no_capture_moves'),
        ),
    ]
