# Generated by Django 4.1.5 on 2023-03-15 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_remove_positionparsed_0_remove_positionparsed_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.training'),
        ),
    ]
