# Generated by Django 4.1.5 on 2023-03-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_training_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainingstats',
            old_name='training_id',
            new_name='training_obj',
        ),
        migrations.AlterField(
            model_name='trainingstats',
            name='successful_branch_runs',
            field=models.IntegerField(default='0', verbose_name='successful_branch_runs'),
        ),
        migrations.AlterField(
            model_name='trainingstats',
            name='successful_runs',
            field=models.IntegerField(default='0', verbose_name='successful_runs'),
        ),
        migrations.AlterField(
            model_name='trainingstats',
            name='total_branch_runs',
            field=models.IntegerField(default='0', verbose_name='total_branch_runs'),
        ),
        migrations.AlterField(
            model_name='trainingstats',
            name='total_runs',
            field=models.IntegerField(default='0', verbose_name='total_runs'),
        ),
    ]
