# Generated by Django 4.1.5 on 2023-03-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_rename_training_id_trainingstats_training_obj_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioninfo',
            name='black_win_percent',
            field=models.FloatField(null=True, verbose_name='black_win_percent'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='white_win_percent',
            field=models.FloatField(null=True, verbose_name='white_win_percent'),
        ),
    ]
