# Generated by Django 3.2 on 2023-04-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0005_alter_positioninfo_black_win_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='positioninfo',
            name='appearances',
            field=models.IntegerField(null=True, verbose_name='appearances'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='cp',
            field=models.IntegerField(null=True, verbose_name='cp'),
        ),
        migrations.AlterField(
            model_name='positioninfo',
            name='mate',
            field=models.IntegerField(null=True, verbose_name='mate'),
        ),
    ]
